### ISSUE TITLE
What is Input ID of movie to view deails: ?

### ISSUE THREAD

**Issue by Dev100194** [aadarshadhakalg/yts-python#1]
**Hi Developer : @aadarshadhakalg** 
**How are u today ?**
**Good .......**

**1.Thank you for your effort on this your project and it's so helpful. **

**2.What is Input ID of movie to view deails even mean? so i can write my choosen answer on the command prompt.**

**3.Please @aadarshadhakalg , Can you write more info in readme file? so we can understand more about your project?**

**4.Keep Safe and Keep Smile.**

**Comment by aadarshadhakalg** [comment]
In input ID field you should input the movie ID number 

Once you browse movies, list of 20 best result will be displayed and you can see ID of the movie in each listing. Same Id you should input to view details.

**Comment by Dev100194** [comment]
thanks a lot @aadarshadhakalg
and thanks for your Golden time 🙏🏻⌚
